### ISSUE TITLE
Mixing naïve and zoned datetimes fails

### ISSUE THREAD

**Issue by kseistrup** [LuRsT/twtxt_on_heroku#1]
The code says

```py
dt = parser.parse(date)
```

and the resulting `dt` object is a zone-naïve datetime object. I.e., the timezone could be anything. The `dt.astimezone()` method seems to assume that `dt` is localtime (_server_ localtime)..

I believe the correct way to get a decent presentation is to add the original timezone from the CSV, and _then_ convert to the display timezone. E.g.:

```py
CSV_TZ = pytz.timezone('Europe/London')
OUT_TZ = pytz.UTC

dt = parser.parse(date).replace(tzinfo=CSV_TZ)
formatted_date = '{:%FT%T%z}'.format(dt.astimezone(OUT_TZ))
```

In effect, what we are saying here is:

1. The datetimes in the CSV are in Europe/London, not the server timezone.
2. Please convert Europe/London to UTC

(I chose two different timezones in order to make the change more obvious.)

----

Apart from that, it appears to me – when I fetch https://twtxt.herokuapp.com/ – that the app is somehow using current time, because the datetimes constantly advance for the same lines (and on top of that the timezone is clearly wrong).

**Comment by LuRsT** [comment]
Hi @kseistrup, thank you so much for the kind bug report and code snippet. 

Dates are a big flaw of mine, so thank you for your explanation, my idea was indeed to add the correct date with my timezone (London) and to let the server convert it, so I'm going to add your snippet into the code (it not only was wrong, but needed a refactor anyway), I will later make the timezone an environment variable so that each user can customise it.

The second :bug: you spotted is because I am using the function `=NOW()` in my google spreadsheet, which apparently changes itself to always be now instead of the timestamp of when I wrote that in the cell :(. I'll need to find a better way of doing it (Open to suggestions if you know :smile: ).

:heart: Thank you so much for your contribution! :heart:
